input_file: "C:\\Users\\Proteomics\\Documents\\PS_922324_Pos_CD_Results_samples_added.xlsx"

n_groups : 6

group_names:
- "Untransfected"
- "Wild_type"
- "G101L"
- "G103L"
- "Empty"
- "G105L"

output_dir: "results"

fdr_threshold: 0.05
logfc_threshold: 1
missingness_threshold: 0.70

name_column: "Name" 
sample_area_prefix: "Area"

# CSV with 2 columns: sample and group
# 'Sample' values must match the sample-area column names *(after the prefix)

group_mapping_file: "C:\\Users\\Proteomics\\Documents\\group_mapping.csv"